### ISSUE TITLE
js and map files being added to the source directories & not gitignored

### ISSUE THREAD

**Issue by kosz** [rangle/angular2-redux-starter#21]
First issue is that they are not gitignored, so they will be committed to the repo on first push. 

Second issue is that they are added next to the actual source file. 

Third issue is that, because they are added next to the source file, this could make excluding them through globs tricky and error prone.

**Comment by SethDavenport** [comment]
@kosz what editor are you using?  I don't run into this with vscode.

**Comment by kosz** [comment]
I am not using an editor to commit to git. 

Looks like our .gitignore was overwritten by a redundant `git init`.

Still not sure if this will fix the processed ES5 files, but will test soon.

**Comment by SethDavenport** [comment]
I'm just a bit confused as to how the `.js` and `.js.map` files are getting generated in the first place.  Webpack doesn't work that way... are you calling `tsc` directly?  Because that shouldn't be necessary; `npm install`, `npm start`, and optionally `npm run dev` should be all you need.

I asked about your editor because I've only seen this type of thing happen with a misconfigured atom ts plugin.

That said, we can add `.js`, `.js.map` to `.gitignore` as long as we don't ignore `webpack.conf.js` or anything under `server` (there's no transpilation on the backend).

**Comment by SethDavenport** [comment]
This turned out to be default behaviour of the atom-typescript plugin.  It can be turned off by adding a couple of keys to `tsconfig.json`.

A fix has been applied to anglular-redux-starter, angular2-redux-starter, and typescript-react-redux-starter.
