### ISSUE TITLE
Can't deploy on Heroku

### ISSUE THREAD

**Issue by kosz** [rangle/angular2-redux-starter#23]
- missing global installs for: webpack, rimraf, tsd and typescript
- webpack and webpack-html-plugin need to be added to dependencies, rather than devDependencies

- other issues, will check later

**Comment by SethDavenport** [comment]
@kosz : this is because Heroku runs `npm install --production`, which ignores devDependencies.  Because we're using webpack, most of the deps are in fact supposed to be in devDependencies.

The solution is to to tell Heroku to run `npm install` normally; you can do this by setting `NPM_CONFIG_PRODUCTION` to `false` in Heroku's 'Settings' page for the app.

**Comment by kosz** [comment]
sounds good, but may be worth considering making it work out of the box, since it may help reduce any potential confusion. 
I may look into some of these things this week, should time allow it.

**Comment by SethDavenport** [comment]
We've gone back and forth about this solution vs. putting everything in 'dependencies'.  I'm agnostic but it would be worth getting Evan's opinion.  That said, if clusternator gets off the ground it will be moot.

**Comment by SethDavenport** [comment]
I've added a note to the README about how to use Heroku.  I've applied the same update to all four starters (angular, angular2, react, typescript-react).
